name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build permissions
      run: ./gradlew :core-data-permissions:build
    - name: Publish permissions
      env:
        PUBLISHER_USERNAME: ${{ secrets.PUBLISHER_USERNAME_2 }}
        PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN_2 }}
      run: ./gradlew :core-data-permissions:publish
